### ISSUE TITLE
Xing Logo anzeigbar machen

### ISSUE THREAD

**Issue by sanddorn** [sparsick/rent-a-dev-team#3]

**Comment by sanddorn** [comment]
Übernehmen der Library aus meinem Blog

**Comment by markusFromGermany** [comment]
![Ihr_Problem](https://user-images.githubusercontent.com/9032818/104849273-181b5200-58e9-11eb-9d3e-68b5beb116fd.PNG)
![Start_Portfolio](https://user-images.githubusercontent.com/9032818/104849278-1b164280-58e9-11eb-85d2-3779f947d2a8.PNG)
![IMG_5109](https://user-images.githubusercontent.com/9032818/104849280-1c476f80-58e9-11eb-97d6-4df83c62ceb9.PNG)

- Aufruf nur via www. möglich
- Link Verteilung steht Meghan drin
- Ich hab mit Portfolio angefangen und dann  Team ausgewählt und beide waren in den Menüs aktiv; dann Portfolio und oben beide Menüpunkt waren aktiv. Rückfragen gerne
